### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by blkbee** [xiaomi-ulysse/android_kernel_xiaomi_msm8937#1]
- [x] Fix missing functions (incomplete code resulting `relocation truncated to fit xxx` compile error)

- [x] Import power, fbdev (Not mandatory ig)

- [ ] 4.9 BRINGUP(COME ON I NEED HELP)

**Comment by zqm64** [comment]
> * [ ]  Fix missing functions (incomplete code resulting `relocation truncated to fit xxx` compile error)
> * [ ]  Import power, fbdev (Not mandatory ig)
> * [ ]  4.9 BRINGUP(COME ON I NEED HELP)

Use the grep tool to find anything missing
For example:
`grep -nr "TheMissingFunctionName" Xiaomi_Kernel_OpenSource/`

**Comment by blkbee** [comment]
seems like caf does not like me, i'll try with older caf tag...

**Comment by blkbee** [comment]
closing issue because all are stable
